---
- hosts: all
  become: true
  tasks:
    - name: Install Apache2 and PHP (Ubuntu only)
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
